FROM amd64/python:3.7

WORKDIR /app

COPY plc_requirements.txt ./
RUN pip install -r plc_requirements.txt

COPY ./examples/plc_server_async.py .

EXPOSE 4840

CMD [ "python3", "-u", "./plc_server_async.py" ]

